# https://www.codeooze.com/webdesign/hugo-new-directory/
# blogdown::serve_site()
baseurl = "/"
languageCode = "en-us"
title = "Wrinkle Hub"
theme = "blackburn"
author = "Meng Xu"
copyright = "&copy; 2019. All rights reserved."
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
 
[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "A collection of sparks"
  brand = "WHub"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "2006 Jan 02, 15:04"

#[menu]
#  # Shown in the side menu.
#  [[menu.main]]
#    name = "Home"
#    pre = "<i class='fa fa-home fa-fw'></i>"
#    weight = 1
#    identifier = "home"
#    url = "/"
    
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
    
  [[menu.main]]
    name = "Assays"
    pre = "<i class='fa fa-list fa-coffee'></i>"
    weight = 3
    identifier = "assay" 
    url = "/assay/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 9
    identifier = "about"
    url = "/about/"
#  [[menu.main]]
#    name = "Contact"
#    pre = "<i class='fa fa-phone fa-fw'></i>"
#    weight = 4
#    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  
  # twitter = "*"
  #facebook = "*"
  #instagram = "*"
  github = "mplusx/mengxu.org"
  #stackoverflow = "*"
  #linkedin = "meng-xu-83046150"